### ISSUE TITLE
Confirmation: What will be the plasma config parameters for mainnet?

### ISSUE THREAD

**Issue by naman-modi** [maticnetwork/maticjs-plasma#3]
In [this file](https://github.com/maticnetwork/maticjs-plasma/blob/main/examples/utils.js) `maticjs-plasma/examples/config.js`, what will be the `plasma` config for mainnet MATIC transactions?

Currently, mentioned in the config examples are:
```
  plasma: {
    parent: {
      erc20: '0x499d11e0b6eac7c0593d8fb292dcbbf815fb29ae',
      erc721: '0xfA08B72137eF907dEB3F202a60EfBc610D2f224b'
    },
    child: {
      erc20: '0xfe4f5145f6e09952a5ba9e956ed0c25e3fa4c7f1',
      erc721: '0x33FC58F12A56280503b04AC7911D1EceEBcE179c'
    },
    registryAddress: '0x56B082d0a590A7ce5d170402D6f7f88B58F71988',
    rootChainAddress: '0x82a72315E16cE224f28E1F1fB97856d3bF83f010', // The address for the main Plasma contract in  Ropsten testnet
    withdrawManagerAddress: '0x3cf9aD3395028a42EAfc949e2EC4588396b8A7D4', // An address for the WithdrawManager contract on Ropsten testnet
    depositManagerAddress: '0x3Bc6701cA1C32BBaC8D1ffA2294EE3444Ad93989' // An address for a DepositManager contract in Ropsten testnet
  },
```

I am doubtful if the same would work for **mainnet v1**, can someone please help with it?

**Comment by ujjwalgupta94** [comment]
no these are for testnet, but all are being handled internally. Just change the address for the token address.

**Comment by ujjwalgupta94** [comment]
Have deleted those unused address, you just have to focus on token address. So whatever token address you want to test on mainnet, just paste the address and everything should work.

Don't forget to change the `network`, `version` in `PlasmaClient` to `mainnet`, `v1` respectively.
